### ISSUE TITLE
victoria pic

### ISSUE THREAD

**Issue by navonacalarco** [CAMH-SCWG/feb-2017-workshops#1]
![screen shot 2017-02-06 at 8 56 19 pm](https://cloud.githubusercontent.com/assets/13733654/22674670/3b7e1f34-ecaf-11e6-8a4c-c3a1919912f5.png)

**Comment by djoverton** [comment]
Just an fyi that you can push the images directly to the repository (a good place would be under the "img" directory); don't need to make an issue!

**Comment by navonacalarco** [comment]
Thanks, Dawson.
